---
title: "Interactive Visualization using Linked Views"
author: Kris Sankaran^[ksankaran@wisc.edu]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interactive Visualization using Linked Views}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library("dplyr")
library("geojsonio")
library("raster")
library("readr")
library("rmapshaper")
library("umap")
library("BIRSBIO2020.scProteomics.embeddings")
```

```{r}
data_dir <- file.path(Sys.getenv("HOME"), "Data")
download_data(data_dir)
loaded_ <- load_mibi(data_dir)
cell_full <- read_csv(file.path(data_dir,  "TNBC_shareCellData", "cellData.csv"))
```

Here's a helper that will prepare the U-Map projection and polygon data for our
downstream plot.

```{r}
input_data <- function(cell_full, tiff_paths, sample_id, crop_size=1000, simplify=0.4) {
  # read the associated raster
  im <- raster(tiff_paths[grepl(paste0("p", sample_id, "_"), tiff_paths)])
  im <- crop(im, extent(im, 0, crop_size, 0, crop_size)) # comment out to work on full data
  polys <- polygonize(im) %>%
    filter(!(cellLabelInImage %in% c(0, 1)))

  # filter down to relevant data
  cell_data <- cell_full %>%
    filter(
      SampleID == sample_id,
      cellLabelInImage %in% polys$cellLabelInImage
    )

  polys <- polys %>%
    left_join(cell_data)

  # run U-Map on channel data
  channels <- setdiff(colnames(cell_data), c("cellLabelInImage", "SampleID", "cellSize", "Background", "tumorYN", "cell_cluster", "tumorCluster", "Group", "immuneCluster", "immuneGroup"))
  dimred <- umap(cell_data[, channels]) %>%
    .[["layout"]] %>%
    data.frame() %>%
    rename(V1 = X1, V2 = X2)
  dimred <- cbind(cell_data, dimred)

  # convert to geojson
  geo_polys <- geojson_json(polys) %>%
    geojson_sp() %>%
    ms_simplify(keep = simplify) %>%
    geojson_json()

  list("dimred" = dimred, "polys" = geo_polys)
}
```

Now we can make this figure for as many patients as we want.

```{r, warning=F, message=F}
data_ <- list()
for (i in seq_len(6)) {
  data_[[i]] <- input_data(cell_full, loaded_$tiffs, i)
}

linked_views(data_[[1]]$polys, data_[[1]]$dimred)
linked_views(data_[[2]]$polys, data_[[2]]$dimred)
linked_views(data_[[3]]$polys, data_[[3]]$dimred)
linked_views(data_[[4]]$polys, data_[[4]]$dimred)
linked_views(data_[[5]]$polys, data_[[5]]$dimred)
linked_views(data_[[6]]$polys, data_[[6]]$dimred)
```
